### ISSUE TITLE
Published wheels don't actually include the DB

### ISSUE THREAD

**Issue by jayclassless** [pyupio/safety-db#2265]
The package on PyPI published for this repository doesn't seem to actually work.

```
(aaa) ~/tmp/aaa:$ pip install --no-cache-dir safety-db
Collecting safety-db
  Downloading https://files.pythonhosted.org/packages/99/f4/2ceadae6059942cbae3d66a789f70dbf871cc9230eacc79ab00d4902bb88/safety_db-2017.4.19-py2.py3-none-any.whl
Installing collected packages: safety-db
Successfully installed safety-db-2017.4.19

(aaa) ~/tmp/aaa:$ python
Python 2.7.14 (default, Feb  6 2018, 20:04:00)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import safety_db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jasonsimeone/tmp/aaa/lib/python2.7/site-packages/safety_db.py", line 13, in <module>
    with open("data/insecure.json") as __f:
IOError: [Errno 2] No such file or directory: 'data/insecure.json'
>>>

(aaa) ~/tmp/aaa:$ find . -name insecure.json
```

Looking in the wheel, the data files aren't there:

```
$ unzip -l safety_db-2017.4.19-py2.py3-none-any.whl
Archive:  safety_db-2017.4.19-py2.py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
      576  04-19-2017 10:11   safety_db.py
     2324  04-19-2017 10:32   safety_db-2017.4.19.dist-info/DESCRIPTION.rst
    19341  04-19-2017 10:32   safety_db-2017.4.19.dist-info/LICENSE.txt
      905  04-19-2017 10:32   safety_db-2017.4.19.dist-info/metadata.json
       10  04-19-2017 10:32   safety_db-2017.4.19.dist-info/top_level.txt
      110  04-19-2017 10:32   safety_db-2017.4.19.dist-info/WHEEL
     3017  04-19-2017 10:32   safety_db-2017.4.19.dist-info/METADATA
      699  04-19-2017 10:32   safety_db-2017.4.19.dist-info/RECORD
---------                     -------
    26982                     8 files
```

**Comment by jayclassless** [comment]
@Jwomers Unfortunately the update to MANIFEST.in didn't fix the wheel distribution. The JSON files are still missing. I believe it's because you're trying to treat them as package data, but you're not actually distributing a python package, just a single module.

Perhaps if the code is reorganized as a package (e.g., as an __init__.py in a directory) and the data directory is a child to that, it'll behave as desired.

```
$ unzip -l safety_db-2018.7.24-py2.py3-none-any.whl
Archive:  safety_db-2018.7.24-py2.py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
      568  07-24-2018 15:14   safety_db.py
    19341  07-24-2018 15:14   safety_db-2018.7.24.dist-info/LICENSE.txt
       10  07-24-2018 15:14   safety_db-2018.7.24.dist-info/top_level.txt
      110  07-24-2018 15:14   safety_db-2018.7.24.dist-info/WHEEL
     3214  07-24-2018 15:14   safety_db-2018.7.24.dist-info/METADATA
      496  07-24-2018 15:14   safety_db-2018.7.24.dist-info/RECORD
---------                     -------
    23739                     6 files
```
