### ISSUE TITLE
Pipenv check failure: Connection to pyup.io timed out

### ISSUE THREAD

**Issue by yyang-nasuni** [pyupio/safety-db#2302]
## Description
Starting from 4/6/2020 morning, the `pipenv check` is failing because connection to safety db timed out. Please see steps below to reproduce issue.

## Details
1. Create a new folder (e.g., `sample`)
2. Change to the new folder.
3. Run `pipenv shell` and `pipenv check`. Following error will be raised and it says the connection to pyup.io is timed out.

```
pipenv check
Checking PEP 508 requirements…
Passed!
Checking installed package safety…
An error occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/urllib3/connection.py", line 141, in _new_conn
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/urllib3/util/connection.py", line 83, in create_connection
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/urllib3/util/connection.py", line 73, in create_connection
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/urllib3/connectionpool.py", line 601, in urlopen
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/urllib3/connectionpool.py", line 346, in _make_request
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/urllib3/connectionpool.py", line 850, in _validate_conn
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/urllib3/connection.py", line 284, in connect
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/urllib3/connection.py", line 146, in _new_conn
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x108044ad0>, 'Connection to pyup.io timed out. (connect timeout=5)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/requests/adapters.py", line 440, in send
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/urllib3/connectionpool.py", line 639, in urlopen
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/urllib3/util/retry.py", line 388, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='pyup.io', port=443): Max retries exceeded with url: /api/v1/safety/insecure.json (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x108044ad0>, 'Connection to pyup.io timed out. (connect timeout=5)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/__main__.py", line 12, in <module>
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/click/core.py", line 722, in __call__
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/click/core.py", line 697, in main
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/click/core.py", line 1066, in invoke
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/click/core.py", line 895, in invoke
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/click/core.py", line 535, in invoke
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/safety/cli.py", line 63, in check
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/safety/safety.py", line 126, in check
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/safety/safety.py", line 108, in fetch_database
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/safety/safety.py", line 79, in fetch_database_url
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/requests/api.py", line 72, in get
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/requests/api.py", line 58, in request
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/requests/sessions.py", line 508, in request
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/requests/sessions.py", line 618, in send
  File "/usr/local/lib/python3.7/site-packages/pipenv/patched/safety.zip/requests/adapters.py", line 496, in send
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='pyup.io', port=443): Max retries exceeded with url: /api/v1/safety/insecure.json (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x108044ad0>, 'Connection to pyup.io timed out. (connect timeout=5)'))
```

**Comment by MartinFalatic** [comment]
The whole pyup.io domain appears to be down at the moment.

https://github.com/pyupio/pyup/issues/379

**Comment by harlekeyn** [comment]
Sorry folks. Our server was down indeed. But it's back up now.

**Comment by yyang-nasuni** [comment]
Thanks for the fix. Pipenv check is working now. All set.
