### ISSUE TITLE
Getting error as FAILED. Kindly help for the solution

### ISSUE THREAD

**Issue by hemantloni** [pyupio/safety-db#2324]
FAIL: test_using_valid_specifier_sets_0000__meta (__main__.TestData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\COMP\AppData\Local\Programs\Python\Python37\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "D:\safety-db-master\tests.py", line 28, in test_using_valid_specifier_sets
    self.failUnless(specifier_set, msg=message)
AssertionError: None is not true : Bad specifier for $meta: 'advisory'

======================================================================
FAIL: test_using_valid_specifier_sets_0001__meta (__main__.TestData)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\COMP\AppData\Local\Programs\Python\Python37\lib\site-packages\parameterized\parameterized.py", line 530, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "D:\safety-db-master\tests.py", line 28, in test_using_valid_specifier_sets
    self.failUnless(specifier_set, msg=message)
AssertionError: None is not true : Bad specifier for $meta: 'timestamp'

----------------------------------------------------------------------
Ran 1903 tests in 7.515s

FAILED (failures=2)

**Comment by SofyaTavrovskaya** [comment]
@hemantloni Problem that in insecure.json and insecure_full.json were added new field, which tests don't understand properly:

`{
    "$meta": {
        "advisory": "PyUp.io metadata",
        "timestamp": 1604210401
    },`

Pull request with fix: https://github.com/pyupio/safety-db/pull/2325

**Comment by yeisonvargasf** [comment]
@SofyaTavrovskaya thank you! your fix was merged, because of that I closed this issue.
